// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRt1UawxAG8LNGzh-aFwhOGrOzLCv370',
    appId: '1:142434808132:android:954c47b451e3f8182b6711',
    messagingSenderId: '142434808132',
    projectId: 'intelligence-personal-advisor',
    databaseURL: 'https://intelligence-personal-advisor-default-rtdb.firebaseio.com',
    storageBucket: 'intelligence-personal-advisor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUYeE48orKRwtYVOgsELNyemUvRdEFQ0',
    appId: '1:142434808132:ios:bcd808d38863fb242b6711',
    messagingSenderId: '142434808132',
    projectId: 'intelligence-personal-advisor',
    databaseURL: 'https://intelligence-personal-advisor-default-rtdb.firebaseio.com',
    storageBucket: 'intelligence-personal-advisor.appspot.com',
    iosBundleId: 'com.ipa.chatbot',
  );
}
